---
version: "3"

services:

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src
    command: /bin/sh -c 'air -c .air.toml'
